language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: lbyXuSNrCE58jfo9PXUJVYCDxCjB0C/On4IpI0SuMq/bPjE9mKsoMOyrw8ch3hcF9lkN8nUFdWqhgZ+ixb5XZk75EsfMMVaPHWd3eIztYbp10T47s4VSb5S/jhGM4wtX+whxBOCl1r3WdVBzoLuefrs9H4xbcNccgqn4zG/XBLP5Fn72pCSX89xTRI5fLP8C64zUPbIIG3HqKAU42WQ3Zwbc83ErRwLXEofeaVIFFaRYDlVC3cwS/3QwNaEqyxBXVc1iuM68lSZj8ApBllacYJBgaRBebYUTK9zPlc3tKZp1/yf8k6ZFDUu294zPP6ftKk9ODU5gHa1P0S6axPReG+WTvUe+ytyaDK5E7YxpfGjee8+UmEeiuC6Ujtef1s0hEQrwh1MtC0dbp17DGy+knRjUEfCz+i+rucYmukNc8yQwpr+x7YLIFZa106N3Ai4lSMW9QOn/jsRj/6cSYozmWeXwe288ZVlOkbVzThNwg+/ourRSXxAYMfdwwlMfqbGY4CoqyzhyI4pRKdG9srhTzZwOBsyhdhJ1vHWauuql5oqUwGCyNUwAxhatOTAPI0w0VgyPZZSPAnM6rmbaY+hAHZPbfy/InILFNJ3OAIMLjMwaO6XOyKcZBDWLnIMCH3vgnMhu4uacjSnLwpD5X5Qh3qF1T1/ov4DjoBxIS7bZBes=
  on_success: never
  on_failure: always