language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: lbyXuSNrCE58jfo9PXUJVYCDxCjB0C/On4IpI0SuMq/bPjE9mKsoMOyrw8ch3hcF9lkN8nUFdWqhgZ+ixb5XZk75EsfMMVaPHWd3eIztYbp10T47s4VSb5S/jhGM4wtX+whxBOCl1r3WdVBzoLuefrs9H4xbcNccgqn4zG/XBLP5Fn72pCSX89xTRI5fLP8C64zUPbIIG3HqKAU42WQ3Zwbc83ErRwLXEofeaVIFFaRYDlVC3cwS/3QwNaEqyxBXVc1iuM68lSZj8ApBllacYJBgaRBebYUTK9zPlc3tKZp1/yf8k6ZFDUu294zPP6ftKk9ODU5gHa1P0S6axPReG+WTvUe+ytyaDK5E7YxpfGjee8+UmEeiuC6Ujtef1s0hEQrwh1MtC0dbp17DGy+knRjUEfCz+i+rucYmukNc8yQwpr+x7YLIFZa106N3Ai4lSMW9QOn/jsRj/6cSYozmWeXwe288ZVlOkbVzThNwg+/ourRSXxAYMfdwwlMfqbGY4CoqyzhyI4pRKdG9srhTzZwOBsyhdhJ1vHWauuql5oqUwGCyNUwAxhatOTAPI0w0VgyPZZSPAnM6rmbaY+hAHZPbfy/InILFNJ3OAIMLjMwaO6XOyKcZBDWLnIMCH3vgnMhu4uacjSnLwpD5X5Qh3qF1T1/ov4DjoBxIS7bZBes=
  on_success: never
  on_failure: always
deploy:
  provider: npm
  email: floyd.price@digital.education.gov.uk
  api_key:
    secure: MkAhskttLXumPPTz3xdWAb6x1Lrd4QEgHyL5PMHFZi6NcdBPiRKI94qfNDBafXnsijNRVhm2DP72u54eLHdqakMCRjtNmMy+sw/vcnqSsdEq5aiuknqLjQsK2Cif6uHcuHSL0lWkIH4KRodkqqMfRNf3j2RENK4NxEqo480PxRy5zORTPpKGwe9Od3oRI97jrGQfnqssWqBtN09iyaJqD90oHJA0rrFZbZwfuOJb8qEmDbswLzilWFGy4fnulC9C3yob7bRZfZ9vkP0JdTQZ0AEhEw9EpdibpJkTJPzdAu/jjDQ8GYLoASsewz+43yGOGNP2KoGREMbU9CXoKtEddTduv3e+5ULq+qbVQRA8an+ZXuRElVizkbrf/rJ3UySpMqm7faCG9mQC9MdPCzS4k4Kbt4wmBYUyhS3izaXQgbXzISY95ifMsPAALcQsd5YkljjTjb8ltsxsU2izEQdhmXvF6uVpwFL1+EPAv9A3PGQoUQn0aegGzd1Hn9J+vARsYPYDplyC7+KImGx1qDN2Q2DhseEQuR5hU50o/7a0Wocj5DK68aSrXOnPS+cLYCA4XF3APYNZ9mv28My4oE+Fqo9jZ3JKF2RmCSaG4hvMmgYkMKteYSjpX+MqDC1soXAd3V7CFUo3UxRC1C+mnBoCueVx+ovJwQt2eafE4C6UfNc=
  on:
    tags: true
    repo: DFE-Digital/login.dfe.jwt-strategies
